name: Nightly Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: sudo apt-get install -y make autoconf gcc

      - name: Configure the project
        run: ./configure

      - name: Build the project
        run: make

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: todolist
          path: ./todolist